name: Build Android APK

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11
  FLUTTER_VERSION: 3.29.2

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Flet
      run: |
        python -m pip install --upgrade pip
        pip install flet

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses
        flutter doctor --android-licenses

    - name: Check environment
      run: flutter doctor -v

    - name: Build APK
      run: |
        flet build apk \
          --build-number $BUILD_NUMBER \
          --build-version $BUILD_VERSION \
          --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/apk/**/*.apk
        retention-days: 30name: Build Android APK & AAB

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11  # إصدار مستقر
  FLUTTER_VERSION: 3.29.2

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [apk, aab]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses || true
        flutter doctor --android-licenses

    - name: Verify Flutter setup
      run: flutter doctor -v

    - name: Build Android ${{ matrix.target }}
      run: |
        flet build ${{ matrix.target }} --build-number $BUILD_NUMBER --build-version $BUILD_VERSION --verbose

    - name: Upload ${{ matrix.target | upcase }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ matrix.target }}
        path: |
          build/${{ matrix.target }}/*.${{ matrix.target }}
          build/${{ matrix.target }}/outputs/**/*
        if-no-files-found: error
        retention-days: 7
